/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface ButtonProps {
  children: React.ReactNode;
  className?: string;
  onClick?: () => void;
}

const Button: React.FC<ButtonProps> = ({ children, className, onClick }) => (
  <button
    className={`px-6 py-3 text-lg font-extrabold leading-5 rounded-md border border-solid ${className}`}
    onClick={onClick}
  >
    {children}
  </button>
);

interface HeadingProps {
  children: React.ReactNode;
}

const Heading: React.FC<HeadingProps> = ({ children }) => (
  <h1 className="text-5xl font-black leading-[53px] max-md:max-w-full">{children}</h1>
);

interface SubheadingProps {
  children: React.ReactNode;
}

const Subheading: React.FC<SubheadingProps> = ({ children }) => (
  <p className="mt-3 text-xl leading-8 max-md:max-w-full">{children}</p>
);

interface HeroProps {
  title: string;
  subtitle: string;
  buttonText: string;
  imageSrc: string;
  imageAlt: string;
  onButtonClick?: () => void;
  builderState: any;
}

const Hero: React.FC<HeroProps> = ({
  title,
  subtitle,
  buttonText,
  imageSrc,
  imageAlt,
  onButtonClick,
  builderState
}) => {
  return (
    <div className="justify-center self-stretch">
      <div className="flex gap-5 max-md:flex-col max-md:gap-0">
        <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
          <div className="flex flex-col grow px-10 pt-14 pb-12 w-full text-justify bg-white max-md:px-5 max-md:max-w-full">
            <div className="flex flex-col justify-center py-20 max-md:max-w-full">
              <div className="flex flex-col mt-16 text-gray-800 max-md:mt-10 max-md:max-w-full">
                <Heading>{title}</Heading>
                <Subheading>{subtitle}</Subheading>
              </div>
              <div>
              {builderState?.state?.article?.data?.blurb}
                </div>
              <Button
                className="self-start my-8 text-indigo-500 border-indigo-500"
                onClick={onButtonClick}
              >
                {buttonText}
              </Button>
            </div>
          </div>
        </div>
        <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
          <div className="flex flex-col grow justify-center max-md:max-w-full">
            <img
              loading="lazy"
              src={imageSrc}
              alt={imageAlt}
              className="w-full aspect-[0.92] max-md:max-w-full"
            />
          </div>
        </div>
      </div>
    </div>
  );
};

export default Hero;