/**
 * This code was generated by Builder.io.
 */
import * as React from "react";
import { Button, Typography, Box } from "@mui/material";
import ArrowRightAltIcon from '@mui/icons-material/ArrowRightAlt';

function MyComponent() {
  return (
    <Box
      sx={{
        alignContent: "center",
        flexWrap: "wrap",
        display: "flex",
        marginTop: "40px",
        paddingRight: { xs: "20px", md: "80px" },
        gap: "16px",
        fontSize: "16px",
        textAlign: "center",
      }}
    >
      <Button
        variant="contained"
        sx={{
          fontFamily: "Roboto, sans-serif",
          justifyContent: "center",
          borderRadius: "32px",
          backgroundColor:
            "var(--primary-phoenix-red-chromatic-phoenix-red-willpower, #DB3725)",
          color: "var(--Neutral-White, #FFF)",
          fontWeight: "500",
          lineHeight: "150%",
          padding: { xs: "0 23px", md: "12px 24px" },
        }}
      >
        Request an LOA
      </Button>
      <Box
        sx={{
          display: "flex",
          gap: "8px",
          color:
            "var(--primary-phoenix-red-chromatic-phoenix-red-willpower, #DB3725)",
          fontWeight: "400",
          margin: "auto 0",
        }}
      >
        <Typography
          variant="body1"
          sx={{
            fontFamily: "Roboto, sans-serif",
          }}
        >
          View LOA Activity
        </Typography>
        <ArrowRightAltIcon sx={{ fontSize: "40px", margin: "auto 0" }} />
      </Box>
    </Box>
  );
}

export default MyComponent;